### ISSUE TITLE
No .profile / .bashrc files

### ISSUE THREAD

**Issue by BahaminShahriari** [BlackCorsair/install-jdk-on-steam-deck#5]
Hello,

I am not very experienced Linux user as most of Steam Deck owners.
I tried installing Java via your script and noticed a small issue where I got a warning, here is the complete Konsole output of the installation:

```
JDK downloaded and extracted into /home/deck/.local/jdk
Setting environment variables if not already set
grep: /home/deck/.profile: No such file or directory
Checking that java is properly installed...
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
Java is succesfully installed!
To activate your java installation execute the following:

        source ~/.bashrc


Done
```

~~I noticed the issue caused by changing my Steam Deck name, so `/home/deck/` became like `/home/Bahamin-s-Deck/`.~~
EDIT: I was wrong and the directory is not related to the device name, so it's still `/home/deck/` after a double check

~~And as the result~~ I am encountering unexpected behavior on every command I send to the Konsole.

The first command I have used was the command I was supposed to use after installation to activate Java:

```
(deck@Bahamin-s-Deck ~)$ source ~/.bashrc
bash: PROMPT_COMMAND: line 3: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 3: `__steamos_prompt_command '(\[\033[1;32m\]\u@\h\[\033[1;34m\] \W\[\033[0m\])\$ '; __steamos_prompt_command '(\[\033[1;32m\]\u@\h\[\033[1;34m\] \W\[\033[0m\])\$ '; __steamos_prompt_command '(\[\033[1;32m\]\u@\h\[\033[1;34m\] \W\[\033[0m\])\$ '; ; '
```

So it doesn't matter what command I use at Konsole, I'll always get this error even if its `ls` command;
What would you suggest to do to fix this issue?

Thanks in advance.

**Comment by BlackCorsair** [comment]
Hi @BahaminShahriari ,
Could you post me your `~/.bashrc` here? Please make sure that there isn't any credentials or secrets before posting it.

To temporary "fix" the warnings, open a konsole terminal and run `sh`. It will run a different 'shell' that won't load (or shouldn't) your  `.bashrc` which contains errors.

**Comment by BlackCorsair** [comment]
it's a bit weird, I ran your `.bashrc` without problems. Do the following and post me all the outputs:
* `ls -la`
* `cat ~/.profile`
* `/bin/bash -lixc exit 2>&1 | sed -n 's/^+* \(source\|\.\) //p'`

I suspect that maybe there's another file that your `bash` is sourcing the cause of the error, because it's executing three times the `__steamos_prompt_command` instead of just one and then does this weird thing: ` ; '`

**Comment by BahaminShahriari** [comment]
Hello, sorry for late response.
Here are my resaults;

```ssh
(deck@Bahamin-s-Deck ~)$ ls -la
total 260
drwx------ 37 deck deck  4096 Jul 30 23:21  .
drwxr-xr-x  5 root root  4096 Jun 18 03:57  ..
drwxr-xr-x  3 deck deck  4096 Jul 14 03:05  Applications
-rw-------  1 deck deck  4046 Jul 27 01:10  .bash_history
-rw-r--r--  1 deck deck    21 Jan  8  2022  .bash_logout
-rw-r--r--  1 deck deck   489 Apr 26  2022  .bash_profile
-rw-r--r--  1 deck deck  2992 Jul 26 14:47  .bashrc
drwxr-xr-x 28 deck deck  4096 Jul 30 23:23  .cache
drwxr-xr-x 32 deck deck  4096 Jul 30 23:26  .config
drwxr-xr-x  2 deck deck  4096 Jul 16 00:55  .cryo_utilities
drwxr-xr-x  3 deck deck  4096 Jul 29 21:59  .deckycache
drwxr-xr-x  2 deck deck  4096 Jul 27 01:19  Desktop
drwxr-xr-x  6 deck deck  4096 Jul 19 14:19  Documents
drwxr-xr-x  6 deck deck  4096 Jul 26 13:14  Downloads
lrwxrwxrwx  1 deck deck   116 Jun 26 00:47 'Elder Scrolls Online' -> '/home/deck/.local/share/Steam/steamapps/compatdata/306130/pfx/drive_c/users/steamuser/Documents/Elder Scrolls Online'
drwxr-xr-x  4 deck deck  4096 Jul 14 02:19  emudeck
drwxr-xr-x  5 deck deck  4096 Jul 12 23:12  .emulationstation
-rw-r--r--  1 deck deck 69974 Feb 10  2022  .face.icon
-rw-r--r--  1 deck deck   110 Jun 18 12:29  .fonts.conf
drwxr-xr-x  3 deck deck  4096 Jul 25 02:18  Games
drwx------  3 deck deck  4096 Jun 26 00:43  .gg.minion.Minion
-rw-r--r--  1 deck deck   270 Jul 30 23:21  .gtkrc-2.0
drwxr-xr-x 10 deck deck  4096 Jul 13 19:43  homebrew
drwxr-xr-x  4 deck deck  4096 Jul 26 14:16  install-jdk-on-steam-deck
drwxr-xr-x  4 deck deck  4096 Jul 27 01:04  .java
drwxr-xr-x  2 deck deck  4096 Jun 29 19:48  .junique
drwxr-xr-x  5 deck deck  4096 Jul 26 14:16  .local
drwxr-xr-x  3 deck deck  4096 Jul 12 23:20  .mame
drwxr-xr-x 15 deck deck  4096 Jul 28 11:15  .minecraft
drwxr-xr-x  3 deck deck  4096 Jun 26 00:47  .minion
drwxr-xr-x  3 deck deck  4096 Jul  3 15:51  Music
-rw-------  1 deck deck   737 Jan 26  2022  .netrc
drwxr-xr-x  4 deck deck  4096 Jul  3 15:51  Pictures
drwx------  3 deck deck  4096 Jun 18 07:30  .pki
-rw-r--r--  1 deck deck    94 Jul 26 14:47  .profile
drwxr-xr-x  2 deck deck  4096 Jun 18 03:57  Public
drwxr-xr-x  2 deck deck  4096 Jun 27 15:49  .renderdoc
drwxr-xr-x  2 deck deck  4096 Jul 13 19:54  sdgyrodsu
drwx------  2 deck deck  4096 Jul 14 17:38  .ssh
drwxr-xr-x  2 deck deck  4096 Jul 30 23:21  .steam
lrwxrwxrwx  1 deck deck    29 Jul 30 23:21  .steampath -> /home/deck/.steam/sdk32/steam
lrwxrwxrwx  1 deck deck    27 Jul 30 23:21  .steampid -> /home/deck/.steam/steam.pid
drwxr-xr-x  2 deck deck  4096 Jun 18 03:57  Templates
drwxr-xr-x  4 deck deck  4096 Jul 29 12:49  .tlauncher
drwxr-xr-x  3 deck deck  4096 Jun 18 12:58  .var
drwxr-xr-x  3 deck deck  4096 Jul 28 17:12  Videos
drwxr-xr-x  3 deck deck  4096 Jul 27 01:12  .vscode
-rw-r--r--  1 deck deck   215 Jun 18 13:59  .wget-hsts
drwxr-xr-x  4 deck deck  4096 Jul 24 00:44  .wine
drwxr-xr-x 15 deck deck  4096 Jul 15 23:02  Zomboid



(deck@Bahamin-s-Deck ~)$ cat ~/.profile
export JAVA_HOME=/home/deck/.local/jdk
export PATH=$PATH:/home/deck/.local/jdk/jdk-17.0.8/bin



(deck@Bahamin-s-Deck ~)$ /bin/bash -lixc exit 2>&1 | sed -n 's/^+* \(source\|\.\) //p'
/etc/profile.d/flatpak-bindir.sh
/etc/profile.d/flatpak.sh
/etc/profile.d/freetype2.sh
/etc/profile.d/gawk.sh
/etc/profile.d/gpm.sh
/etc/profile.d/kde.sh
/etc/profile.d/libva.sh
/etc/profile.d/locale.sh
/etc/profile.d/perlbin.sh
/etc/profile.d/steamos.sh
/etc/bash.bashrc
/usr/share/bash-completion/bash_completion
/home/deck/.bashrc
/home/deck/.profile
```

**Comment by BahaminShahriari** [comment]
> Hold up a minute... is the error still happening? I'm not seeing that error while you run the commands.

Those errors only appears after I use `source ~/.bashrc` command, and they will go away if I open a new Konsole.

I mean, the Java works perfectly if I write a bash script to locate the java bin first then locate my java file after using `-java` command, but it does not open the Java file by double clicking as it's not added to PATH correctly.



> /etc/profile.d/flatpak-bindir.sh
> /etc/profile.d/flatpak.sh
> /etc/profile.d/freetype2.sh
> /etc/profile.d/gawk.sh
> /etc/profile.d/gpm.sh
> /etc/profile.d/kde.sh
> /etc/profile.d/libva.sh
> /etc/profile.d/locale.sh
> /etc/profile.d/perlbin.sh
> /etc/profile.d/steamos.sh

All these bash scripts are seeming to be default files, as I didn't touch them manually. But there might be something that decky loader have done to them, I'm not quite sure.

**Comment by rasitayaz** [comment]
I'm getting the same prompts when I type `source ~/.bashrc` but java works. might be an issue related to the default `.bashrc` of steamos at the stable channel.

**Comment by rasitayaz** [comment]
also, shouldn't `JAVA_HOME` be set to `/home/deck/.local/jdk/jdk-17.0.8` instead of `/home/deck/.local/jdk`?

**Comment by BlackCorsair** [comment]
hey! I'm sorry I let you waiting for so long @BahaminShahriari 

@rasitayaz 
> might be an issue related to the default .bashrc of steamos at the stable channel

It is! Just checked with my own SteamDeck, which I didn't reinstall the OS since it came to me on October 2022, and I had the following:
```bash
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
```

After pasting the `bashrc` from @BahaminShahriari (I asumed that we all had the same file) , I've also encountered the same error. But the error persists even I you don't run my script or even if you "uninstall" it.

Your `bashrc` appears to be the same as the one in `/etc/bash.bashrc`, only that the one I have in `/etc` also has the following line:
```bash
[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
```

Which just checks that the `bash_completion` exists before loading it.

The issue is definitively this line:
```bash
PROMPT_COMMAND="__steamos_prompt_command '$PS1'${PROMPT_COMMAND:+; $PROMPT_COMMAND; }"
```
I'm not really sure why they're concatenating the `PROMPT_COMMAND`, but that line is the issue.

On the bright side, even if you don't use `source ~/.bashrc` you can start using the java installation as soon as you open a new terminal or a new `bash` shell... but that isn't really a solution.

What I've found it works, it's removing the `'${PROMPT_COMMAND:+; $PROMPT_COMMAND; }`. Once it's no longer on the file, I'm not encountering anymore the issue. I'll try to get in touch with valve asking about the `bashrc` so they may enlighten us.

@rasitayaz 
> also, shouldn't JAVA_HOME be set to /home/deck/.local/jdk/jdk-17.0.8 instead of /home/deck/.local/jdk?

Looking at [oracle's page](https://docs.oracle.com/en/cloud/saas/enterprise-performance-management-common/diepm/epm_set_java_home_104x6dd63633_106x6dd6441c.html) I think it's fine. Although it's true it should be better to use the `$JAVA_HOME` variable instead in the `PATH` variable instead of setting the full path... DRY

From this issue I'll make a PR removing the `source ~/.bashrc` part of the guide until this is worked out. Also I'll finally add the "how to uninstall" guide and maybe later a script.

BR

**Comment by rasitayaz** [comment]
> also, shouldn't `JAVA_HOME` be set to `/home/deck/.local/jdk/jdk-17.0.8` instead of `/home/deck/.local/jdk`?

I tried to run a java program that checks `JAVA_HOME` for the jre installation, and it was saying that the environment variable is set to an invalid path. changing it to `/home/deck/.local/jdk/jdk-17.0.8` solved the problem.
