### ISSUE TITLE
Um Environment Variables?

### ISSUE THREAD

**Issue by sevrick** [BlackCorsair/install-jdk-on-steam-deck#8]
Ok so you lost me at Environment Variables. Am I supposed to create a folder .profile? Because there isn't one there now. I tried educating my self on environment variables but not sure I am supposed to use them in context with what we are doing here. I don't suppose you have video tutorial?

**Comment by BlackCorsair** [comment]
Hi @sevrick ,
If you saw an error while executing the script like the following:
`grep: /home/deck/.profile: No such file or directory`

Don't worry, because the script will then create the **file** `~/.profile`.

*BUT* that error shouldn't appear, so I fixed it in a recent commit -> https://github.com/BlackCorsair/install-jdk-on-steam-deck/commit/cfcd335343608410fa44c0f6e9f3fedcabb2bea7

>  Am I supposed to create a folder .profile?
Nope, the script takes care or it. But `.profile` is a file, not a directory.

>  I don't suppose you have video tutorial?
Also nope, I don't have a youtube channel or anything like that. But the script should be pretty easy to use, just follow the steps in: https://github.com/BlackCorsair/install-jdk-on-steam-deck#usage

There's a final message when you launch the script:
```
To start using this java installation, open a new terminal or start a new shell by running 'bash'
    
Originally you could run 'source ~/.bashrc', but since some time there's an issue with it
or more info check the issue: https://github.com/BlackCorsair/install-jdk-on-steam-deck/issues/5
```
Just run `bash` in your terminal or open a new one to start using java.

BR

**Comment by sevrick** [comment]
So I was confused when you said "Exec a checksum of the file using the official sha256 checksum"
I assumed it ment copy the linux link and paste it into a the terminal and run it. Which I did and it said it successfully installed but how do I run my .jar file now that it is installed?
